#!/usr/bin/env python3
"""Build claim-level evidence artifacts for the TMS training platform."""

from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
LIT_DIR = PROJECT_ROOT / "literature_search"
RECORDS_PATH = LIT_DIR / "pubmed_records.csv"
CLAIMS_PATH = LIT_DIR / "evidence_claims.csv"
PATIENT_MD = LIT_DIR / "patient_faq_claims.md"
TECH_MD = LIT_DIR / "technician_workflow_claims.md"
COVERAGE_MD = LIT_DIR / "claim_source_coverage.md"


CLAIMS = [
    {
        "id": "MEC-001",
        "module": "Mechanisms",
        "audience": "patient_and_technician",
        "question": "What does the magnetic pulse do?",
        "claim": "A TMS coil carries a brief current pulse that creates a changing magnetic field, which induces an electric field in nearby brain tissue.",
        "patient_answer": "The coil does not put electricity directly through the scalp. It uses a magnetic pulse to induce tiny electrical currents in the targeted brain area.",
        "technician_detail": "Dose at cortex depends on coil type, location, orientation, intensity, scalp-to-cortex distance, and anatomy.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552",
        "clinical_action": "Use this wording to explain basic mechanism without implying direct electrical injection.",
        "caveat": "This is a physical mechanism claim, not a guarantee of clinical response.",
    },
    {
        "id": "MEC-002",
        "module": "Mechanisms",
        "audience": "patient_and_technician",
        "question": "Why are treatments repeated over many sessions?",
        "claim": "Repeated TMS sessions are intended to produce cumulative changes in cortical excitability and network function, not just a transient sensation during the session.",
        "patient_answer": "The benefit is usually expected to build over repeated sessions, much like practicing a pattern with the brain rather than flipping an instant switch.",
        "technician_detail": "Avoid promising same-day improvement; treatment effects can emerge gradually and vary across protocols and patients.",
        "evidence_strength": "strong",
        "source_pmids": "31901449; 28541649; 27090022",
        "clinical_action": "Frame adherence as part of cumulative dosing.",
        "caveat": "Individual response timing varies and depends on diagnosis, protocol, and patient factors.",
    },
    {
        "id": "MEC-003",
        "module": "Mechanisms",
        "audience": "technician",
        "question": "What is theta burst stimulation?",
        "claim": "Theta burst stimulation uses patterned bursts of pulses designed to produce lasting excitability changes with shorter stimulation times than many conventional rTMS protocols.",
        "patient_answer": "Theta burst is a shorter patterned form of TMS. The pattern is chosen because it can affect brain excitability efficiently.",
        "technician_detail": "Classic motor-cortex studies found iTBS and cTBS can shift excitability in different directions, but individual responses are variable.",
        "evidence_strength": "moderate",
        "source_pmids": "15664172; 18566003; 21221011",
        "clinical_action": "Teach iTBS/cTBS as protocol-specific patterns, not interchangeable abbreviations.",
        "caveat": "Motor-cortex physiology does not translate perfectly to every psychiatric target.",
    },
    {
        "id": "MEC-004",
        "module": "Mechanisms",
        "audience": "patient_and_technician",
        "question": "Why target the DLPFC in depression?",
        "claim": "Depression protocols commonly target prefrontal regions, especially left DLPFC, because these regions participate in mood-relevant cognitive-control and limbic networks.",
        "patient_answer": "For depression, TMS usually targets a frontal brain network involved in mood regulation, attention, and emotional control.",
        "technician_detail": "Do not describe DLPFC as a single depression switch. It is a network target with protocol- and localization-dependent effects.",
        "evidence_strength": "strong",
        "source_pmids": "28541649; 27090022; 17573044; 31901449",
        "clinical_action": "Use network language in patient education.",
        "caveat": "Exact target selection varies by clinic, device, diagnosis, and protocol.",
    },
    {
        "id": "MEC-005",
        "module": "Mechanisms",
        "audience": "patient_and_technician",
        "question": "Is motor threshold a depression measure?",
        "claim": "Resting motor threshold is a calibration measure of motor-cortex excitability used to scale stimulation intensity, not a measure of mood severity.",
        "patient_answer": "The thumb or hand twitch test helps set a personalized treatment dose. It is not a test of how depressed you are.",
        "technician_detail": "RMT should be documented as a dosing calibration variable with method and muscle/site details.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 41949547; 42082007",
        "clinical_action": "Correct patient misconceptions during mapping.",
        "caveat": "Some research links excitability metrics to physiology, but clinical dosing use is the main technician-facing point.",
    },
    {
        "id": "MEC-006",
        "module": "Mechanisms",
        "audience": "technician",
        "question": "Why is brain state consistency emphasized?",
        "claim": "TMS effects are state-dependent: sleep, caffeine, medications, cortical excitability, attention, and time of day can alter neurophysiological responses.",
        "patient_answer": "Keeping your usual routine steady helps the clinic stimulate under similar conditions each day.",
        "technician_detail": "Record meaningful state changes and notify the prescriber when changes could affect safety, tolerability, or dosing.",
        "evidence_strength": "moderate",
        "source_pmids": "37738899; 39756660; 41346487; 36911138; 34872405",
        "clinical_action": "Ask about major changes before sessions and document them.",
        "caveat": "Evidence is stronger for neurophysiologic variability than for simple rules that guarantee better clinical response.",
    },
    {
        "id": "MEC-007",
        "module": "Mechanisms",
        "audience": "patient_and_technician",
        "question": "Can behavior make TMS work better?",
        "claim": "Consistent sleep, caffeine, medications, and substance use can reduce avoidable variability, but evidence does not support promising that any single behavior will make TMS work.",
        "patient_answer": "The best practical advice is consistency: keep your normal caffeine, sleep, and medication routine unless your clinician changes it.",
        "technician_detail": "Avoid coaching patients to increase caffeine, skip medicines, or change sleep to chase a stronger effect.",
        "evidence_strength": "moderate",
        "source_pmids": "33243615; 39756660; 41346487; 36911138; 34872405",
        "clinical_action": "Use consistency language rather than optimization claims.",
        "caveat": "Patient-specific medical advice belongs to the treating clinician.",
    },
    {
        "id": "MEC-008",
        "module": "Mechanisms",
        "audience": "technician",
        "question": "How should we discuss biomarkers?",
        "claim": "EEG, qEEG, fNIRS, and TMS-EEG biomarkers are promising but should be presented as emerging tools unless locally validated for a defined clinical decision.",
        "patient_answer": "Some clinics and studies measure brain signals around TMS, but these tests do not yet provide a guaranteed prediction for every patient.",
        "technician_detail": "Label biomarker workflows as research, exploratory, or validated according to the clinic's actual protocol and evidence.",
        "evidence_strength": "moderate",
        "source_pmids": "41483580; 42066923; 42055012",
        "clinical_action": "Prevent overinterpretation of qEEG/fNIRS readouts.",
        "caveat": "Specific devices or algorithms may have local validation not captured by broad PubMed screening.",
    },
    {
        "id": "SAF-001",
        "module": "Safety and Side Effects",
        "audience": "patient_and_technician",
        "question": "What side effects are common?",
        "claim": "The common side effects of TMS are usually local and transient, especially scalp discomfort, headache, facial muscle twitching, and fatigue.",
        "patient_answer": "The most common issues are temporary scalp discomfort or headache. Tell staff if it becomes intense or different from usual.",
        "technician_detail": "Track side effect type, intensity, timing, protocol changes, and whether intervention was needed.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552; 28541649; 27090022",
        "clinical_action": "Normalize expected sensations while keeping adverse-event reporting active.",
        "caveat": "Side effect profile varies by protocol, coil, target, intensity, and patient history.",
    },
    {
        "id": "SAF-002",
        "module": "Safety and Side Effects",
        "audience": "patient_and_technician",
        "question": "How rare are seizures?",
        "claim": "TMS-associated seizure is rare when modern safety guidelines and screening are followed, but it is the key serious acute risk technicians must be prepared for.",
        "patient_answer": "Seizures are rare, but the clinic screens carefully because safety matters.",
        "technician_detail": "Know the clinic seizure-response procedure, stop stimulation immediately, protect the patient, and summon medical help.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552; 34133991; 9474057",
        "clinical_action": "Use screening and emergency readiness as core competencies.",
        "caveat": "Risk is not zero and can change with sleep loss, medications, substances, neurological illness, and protocol parameters.",
    },
    {
        "id": "SAF-003",
        "module": "Safety and Side Effects",
        "audience": "patient_and_technician",
        "question": "Why use ear protection?",
        "claim": "Ear protection is recommended because the coil click can be loud, even though permanent hearing injury is not expected when appropriate precautions are used.",
        "patient_answer": "The earplugs are for the loud clicking sound from the coil.",
        "technician_detail": "Confirm hearing protection before each session and document exceptions according to policy.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552; 1549231",
        "clinical_action": "Make ear protection a non-negotiable setup step.",
        "caveat": "Patients with hearing devices or auditory sensitivity may need clinician-specific handling.",
    },
    {
        "id": "SAF-004",
        "module": "Safety and Side Effects",
        "audience": "technician",
        "question": "What must be screened before treatment?",
        "claim": "TMS screening should cover seizure history, neurological illness, implanted or ferromagnetic material, electronic devices, pregnancy status where relevant, medication/substance changes, and prior adverse reactions.",
        "patient_answer": "The safety questions check for rare situations where magnetic stimulation may need special review.",
        "technician_detail": "Use the clinic's formal checklist and escalate changes rather than making independent clearance decisions.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552; 11332408",
        "clinical_action": "Run an update screen at baseline and before sessions as local policy requires.",
        "caveat": "Final eligibility decisions are clinician responsibilities.",
    },
    {
        "id": "SAF-005",
        "module": "Safety and Side Effects",
        "audience": "technician",
        "question": "What symptoms require escalation?",
        "claim": "Seizure, loss of consciousness, syncope, chest pain, new neurological symptoms, severe unusual headache, mania/hypomania symptoms, or persistent confusion require immediate escalation.",
        "patient_answer": "Tell staff right away if anything feels severe, unusual, or not like your normal treatment sensation.",
        "technician_detail": "Stop stimulation and follow emergency or prescriber-notification policy; document objective observations.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552; 28541649",
        "clinical_action": "Build escalation triggers into technician training.",
        "caveat": "Clinics should adapt wording to local medical protocols.",
    },
    {
        "id": "SAF-006",
        "module": "Safety and Side Effects",
        "audience": "technician",
        "question": "Are theta burst protocols safe?",
        "claim": "Theta burst stimulation has a safety literature, but safety depends on protocol parameters, patient selection, and adherence to updated guidelines.",
        "patient_answer": "Shorter protocols still follow safety rules. Shorter does not mean casual.",
        "technician_detail": "Verify exact iTBS/cTBS protocol, intensity, train structure, pulse count, and contraindication screening.",
        "evidence_strength": "moderate",
        "source_pmids": "21221011; 33243615; 29726344",
        "clinical_action": "Treat TBS setup as protocol-specific, not as a generic shorter rTMS.",
        "caveat": "Older safety reviews predate some accelerated protocols.",
    },
    {
        "id": "SAF-007",
        "module": "Safety and Side Effects",
        "audience": "technician",
        "question": "How should medication changes be handled?",
        "claim": "Medication changes can affect seizure threshold, cortical excitability, tolerability, and possibly clinical response, so technicians should document changes and alert the treating clinician.",
        "patient_answer": "Take medications as prescribed and tell us about changes. Do not stop or change medicines for TMS unless your clinician tells you to.",
        "technician_detail": "Pay special attention to benzodiazepines, anticonvulsants, stimulants, substances, and medications known to affect seizure threshold.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552; 38299320; 31368628",
        "clinical_action": "Create a medication-change escalation rule.",
        "caveat": "Evidence on benzodiazepines and efficacy is mixed; safety review is separate from efficacy speculation.",
    },
    {
        "id": "SAF-008",
        "module": "Safety and Side Effects",
        "audience": "patient_and_technician",
        "question": "Can TMS trigger mania?",
        "claim": "Mood switching or mania/hypomania is uncommon but clinically important, especially in bipolar-spectrum illness or when symptoms change rapidly.",
        "patient_answer": "Report unusually elevated mood, decreased need for sleep, impulsivity, agitation, or feeling unlike yourself.",
        "technician_detail": "Escalate suspected manic or mixed symptoms to the treating clinician before continuing treatment.",
        "evidence_strength": "moderate",
        "source_pmids": "33243615; 28541649; 31901449",
        "clinical_action": "Include mania symptom prompts in safety training.",
        "caveat": "Risk assessment is diagnosis- and medication-dependent.",
    },
    {
        "id": "FAQ-001",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "Why does it feel like tapping?",
        "claim": "The tapping sensation is usually from magnetic pulses activating scalp nerves and muscles near the coil, not from tissue damage.",
        "patient_answer": "The tapping or pulsing feeling is expected. It comes from the pulse and nearby scalp muscles/nerves reacting.",
        "technician_detail": "Differentiate expected tapping from sharp, escalating, or unusual pain.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552",
        "clinical_action": "Use during first-session coaching.",
        "caveat": "Painful or unusual sensations still need assessment.",
    },
    {
        "id": "FAQ-002",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "Should I keep caffeine the same?",
        "claim": "Caffeine can affect cortical excitability and may moderate TMS-related plasticity or outcomes, so consistency is more defensible than increasing or stopping caffeine abruptly.",
        "patient_answer": "Try to have about your usual amount of caffeine each treatment day unless your clinician advises otherwise.",
        "technician_detail": "Document major caffeine changes, especially around motor threshold changes, discomfort, anxiety, or sleep disruption.",
        "evidence_strength": "moderate",
        "source_pmids": "41346487; 36911138; 34872405",
        "clinical_action": "Teach consistency, not caffeine optimization.",
        "caveat": "Evidence is still emerging and does not define a universal caffeine dose.",
    },
    {
        "id": "FAQ-003",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "Does sleep matter?",
        "claim": "Sleep deprivation can change cortical excitability and may affect mood, tolerability, and treatment-day brain state.",
        "patient_answer": "Aim for your usual sleep schedule and tell us if you slept very poorly or stayed up all night.",
        "technician_detail": "Sleep deprivation is a safety and state-dependence flag, especially if combined with medication or substance changes.",
        "evidence_strength": "moderate",
        "source_pmids": "39756660; 33243615",
        "clinical_action": "Add sleep-change prompts to daily check-in.",
        "caveat": "The evidence does not support a single sleep-hour cutoff for all patients.",
    },
    {
        "id": "FAQ-004",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "Should I take my medications as usual?",
        "claim": "Patients should take medications as prescribed and report changes; technicians should not advise medication changes to influence TMS response.",
        "patient_answer": "Take your medications the usual way unless your prescriber tells you otherwise, and tell us about any changes.",
        "technician_detail": "Medication changes are clinician-review items because they can affect seizure threshold, excitability, and symptoms.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552; 28541649",
        "clinical_action": "Make medication consistency part of patient onboarding.",
        "caveat": "Urgent medication questions should be routed to the prescriber.",
    },
    {
        "id": "FAQ-005",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "What if I miss a session?",
        "claim": "TMS protocols are designed as repeated courses, so missed sessions should be handled according to prescriber and clinic protocol rather than made up casually.",
        "patient_answer": "Call the clinic if you miss a session. Do not try to double up unless the treatment team specifically schedules it.",
        "technician_detail": "Document missed sessions and follow local rules for makeups, extension, or prescriber review.",
        "evidence_strength": "clinic-policy-dependent",
        "source_pmids": "28541649; 27090022",
        "clinical_action": "Build a missed-session workflow.",
        "caveat": "Published guidelines do not replace device- and clinic-specific orders.",
    },
    {
        "id": "FAQ-006",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "When should I expect improvement?",
        "claim": "Antidepressant response often emerges over a course of treatment, and early nonresponse does not mean the course has failed.",
        "patient_answer": "Some people notice changes early, but many need multiple weeks. Keep reporting symptoms honestly as treatment continues.",
        "technician_detail": "Use validated scales and prescriber review rather than informal technician impressions.",
        "evidence_strength": "strong",
        "source_pmids": "17573044; 28541649; 27090022",
        "clinical_action": "Set expectations at intake and reinforce during the course.",
        "caveat": "Accelerated protocols may have different response timing.",
    },
    {
        "id": "FAQ-007",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "Can I drink alcohol or use cannabis during the course?",
        "claim": "Substance use changes can affect sleep, seizure threshold, mood, and treatment-day brain state, so they should be reported and handled by clinical policy.",
        "patient_answer": "Tell the clinic about alcohol, cannabis, or other substance changes. The goal is safety and consistent treatment conditions.",
        "technician_detail": "Escalate intoxication, withdrawal concern, or major use changes before treatment.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552",
        "clinical_action": "Include substance-use changes in daily screening.",
        "caveat": "Specific abstinence rules vary by clinic and diagnosis.",
    },
    {
        "id": "FAQ-008",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "Is discomfort a sign that treatment is working?",
        "claim": "Discomfort is not a reliable sign of efficacy; stimulation should be tolerable while still following the prescribed intensity and target.",
        "patient_answer": "Stronger pain does not mean better treatment. Tell us if it hurts so we can assess it.",
        "technician_detail": "Do not trade tolerability for unapproved dose changes. Use protocol-approved comfort adjustments.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 28541649",
        "clinical_action": "Correct the 'pain equals efficacy' misconception.",
        "caveat": "Some protocols may include ramping or adaptation periods.",
    },
    {
        "id": "FAQ-009",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "Why do you ask the same questions every day?",
        "claim": "Repeated screening catches changes in safety status, medication/substance state, sleep, and symptoms that may matter for that day's treatment.",
        "patient_answer": "The daily questions are a safety check. Your answers help us know whether anything changed since the last session.",
        "technician_detail": "Daily screening should be brief, consistent, documented, and escalated when positive.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 11332408",
        "clinical_action": "Explain repetitive screening as active safety work.",
        "caveat": "Exact daily checklist content is clinic-specific.",
    },
    {
        "id": "FAQ-010",
        "module": "Patient FAQ",
        "audience": "patient",
        "question": "What should I report between sessions?",
        "claim": "Patients should report new neurological events, fainting, severe or unusual headache, medication changes, substance changes, pregnancy status changes, mania symptoms, and worsening suicidality.",
        "patient_answer": "Report anything medically significant or unusual, especially medication changes, fainting, seizure-like events, severe headache, or major mood changes.",
        "technician_detail": "Have a clear path for urgent psychiatric symptoms and medical events.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552; 28541649",
        "clinical_action": "Include in written patient onboarding.",
        "caveat": "Emergency symptoms require emergency care, not just next-session reporting.",
    },
    {
        "id": "TEC-001",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "What must be verified before each session?",
        "claim": "Before each session, technicians should verify patient identity, treatment order, site/target, protocol, intensity, session number, contraindication updates, ear protection, and adverse events since last session.",
        "patient_answer": "We verify details each day to make sure the treatment matches your prescription and safety status.",
        "technician_detail": "Use a forced checklist rather than memory for setup-critical steps.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 28541649; 27090022",
        "clinical_action": "Convert to a pre-session checklist.",
        "caveat": "Device-specific checks should be added from manufacturer manuals.",
    },
    {
        "id": "TEC-002",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "What should be documented?",
        "claim": "Each treatment record should document target/localization method, coil orientation, intensity, motor threshold basis, pulse/train parameters, patient state changes, tolerability, and adverse events.",
        "patient_answer": "The treatment log helps the team keep sessions consistent.",
        "technician_detail": "Documentation is part of dose fidelity, not clerical afterthought.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 28541649; 27090022",
        "clinical_action": "Audit charts for dose-fidelity fields.",
        "caveat": "Exact fields vary by device and clinic.",
    },
    {
        "id": "TEC-003",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "How should RMT be measured?",
        "claim": "RMT should be measured with a defined, reproducible method and sufficient observations, with the method documented so later changes can be interpreted.",
        "patient_answer": "The mapping step personalizes the dose.",
        "technician_detail": "Methods include Rossini-Rothwell-style thresholding, adaptive threshold hunting, and emerging automated tools; clinics should validate their method.",
        "evidence_strength": "strong",
        "source_pmids": "41949547; 42082007; 33243615",
        "clinical_action": "Train technicians to one clinic-standard MT method before independent operation.",
        "caveat": "Visual twitch detection and EMG-based methods may differ.",
    },
    {
        "id": "TEC-004",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "When should RMT be rechecked?",
        "claim": "RMT should be rechecked according to clinic protocol and when meaningful clinical-state changes occur, such as medication changes, major sleep deprivation, neurological events, long treatment gaps, or unexpected tolerability/motor findings.",
        "patient_answer": "Sometimes we repeat mapping because your brain-state or medication situation changed.",
        "technician_detail": "Escalate possible RMT-shifting changes rather than silently continuing the old dose.",
        "evidence_strength": "moderate",
        "source_pmids": "33243615; 37738899; 41949547",
        "clinical_action": "Define RMT recheck triggers in the SOP.",
        "caveat": "Published evidence does not define one universal recheck interval.",
    },
    {
        "id": "TEC-005",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "Does time of day matter?",
        "claim": "Time of day can influence resting motor threshold in clinical practice, so consistent scheduling may reduce avoidable variability when feasible.",
        "patient_answer": "We try to keep treatment conditions consistent when possible.",
        "technician_detail": "Do not delay clinically needed care solely for time matching, but note large schedule shifts if MT or tolerability changes.",
        "evidence_strength": "limited",
        "source_pmids": "37738899",
        "clinical_action": "Record schedule changes during troubleshooting.",
        "caveat": "Time-of-day effects are not yet a universal dosing rule.",
    },
    {
        "id": "TEC-006",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "How should targeting methods be taught?",
        "claim": "Scalp-based targeting, Beam F3, 5 cm/5.5 cm rules, neuronavigation, and circuit-guided methods are not interchangeable; each has assumptions and documentation requirements.",
        "patient_answer": "The team uses a specific method to place the coil consistently over the intended target.",
        "technician_detail": "If the clinic changes targeting method, the chart should preserve which method was used and why.",
        "evidence_strength": "strong",
        "source_pmids": "32289680; 37714408; 33243615",
        "clinical_action": "Train target localization as a named workflow, not a general scalp location.",
        "caveat": "Clinical superiority between practical targeting methods may be context-specific.",
    },
    {
        "id": "TEC-007",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "How does Beam F3 compare with 5.5 cm targeting?",
        "claim": "Studies comparing Beam F3 and 5.5 cm targeting in depression suggest similar effectiveness in some clinical contexts, but reliability and patient anatomy remain important.",
        "patient_answer": "Different clinics may use different validated placement methods.",
        "technician_detail": "Do not mix targeting rules mid-course unless directed and documented.",
        "evidence_strength": "moderate",
        "source_pmids": "32289680; 37714408",
        "clinical_action": "Use one target method consistently within a course unless ordered otherwise.",
        "caveat": "This does not prove all targeting methods are equivalent.",
    },
    {
        "id": "TEC-008",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "Why does coil orientation matter?",
        "claim": "Coil position and orientation affect induced electric-field direction and stimulation of intended tissue, so drift and rotation are dose-fidelity problems.",
        "patient_answer": "We keep the coil steady because small position changes can change what is stimulated.",
        "technician_detail": "Use marks, neuronavigation, fixtures, and repeated checks according to device and clinic workflow.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552",
        "clinical_action": "Include coil drift checks during treatment.",
        "caveat": "Exact tolerances depend on target, device, and localization method.",
    },
    {
        "id": "TEC-009",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "Can technicians change intensity for comfort?",
        "claim": "Technicians should use only protocol-approved comfort adjustments and should not independently change prescribed treatment dose or protocol.",
        "patient_answer": "Tell us if it hurts; we can assess comfort while staying within the prescribed treatment plan.",
        "technician_detail": "Escalate persistent intolerance; document any ramping, pauses, or clinician-approved changes.",
        "evidence_strength": "strong",
        "source_pmids": "28541649; 27090022; 33243615",
        "clinical_action": "Define allowed comfort adjustments in SOP.",
        "caveat": "Local scope-of-practice rules control who may adjust what.",
    },
    {
        "id": "TEC-010",
        "module": "Technician Workflow",
        "audience": "technician",
        "question": "How should a seizure be handled?",
        "claim": "If a seizure occurs, stimulation should stop immediately and staff should follow emergency protocol focused on patient safety and rapid medical evaluation.",
        "patient_answer": "The clinic has a safety plan for rare emergencies.",
        "technician_detail": "Protect from injury, time the event, avoid putting anything in the mouth, and summon medical help per protocol.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 19833552; 34133991",
        "clinical_action": "Drill seizure-response workflow.",
        "caveat": "Emergency instructions must match local medical governance.",
    },
    {
        "id": "PRO-001",
        "module": "Protocol Literacy",
        "audience": "patient_and_technician",
        "question": "What protocols are best established for depression?",
        "claim": "High-frequency left prefrontal rTMS and several related prefrontal protocols have established evidence for major depressive disorder, with protocol-specific indications and parameters.",
        "patient_answer": "For depression, TMS usually uses a studied prefrontal protocol repeated across a treatment course.",
        "technician_detail": "Confirm indication, target, frequency, intensity, train structure, pulses, and total sessions against the written order.",
        "evidence_strength": "strong",
        "source_pmids": "17573044; 28541649; 27090022; 31901449",
        "clinical_action": "Teach protocol literacy before device operation.",
        "caveat": "Guideline support varies by indication and protocol.",
    },
    {
        "id": "PRO-002",
        "module": "Protocol Literacy",
        "audience": "patient_and_technician",
        "question": "How does iTBS compare with 10 Hz rTMS for depression?",
        "claim": "The THREE-D trial found intermittent theta burst stimulation was non-inferior to standard high-frequency rTMS for treatment-resistant depression, with much shorter sessions.",
        "patient_answer": "Some shorter TMS protocols have evidence comparable to longer standard sessions for depression.",
        "technician_detail": "Shorter session length does not mean lower need for exact targeting, dose, and safety checks.",
        "evidence_strength": "strong",
        "source_pmids": "29726344",
        "clinical_action": "Teach iTBS as evidence-based but protocol-specific.",
        "caveat": "Non-inferiority was shown for a defined population and protocol.",
    },
    {
        "id": "PRO-003",
        "module": "Protocol Literacy",
        "audience": "technician",
        "question": "Are low-frequency right-sided and bilateral protocols evidence-based?",
        "claim": "Low-frequency right prefrontal and bilateral protocols have supporting evidence, but strength and parameters differ from standard left-sided high-frequency protocols.",
        "patient_answer": "Different TMS patterns can be chosen for different clinical reasons.",
        "technician_detail": "Do not generalize setup parameters from one protocol to another.",
        "evidence_strength": "strong",
        "source_pmids": "31901449; 28541649; 27090022",
        "clinical_action": "Separate protocol cards by frequency/side/target.",
        "caveat": "Local payer and device indications may be narrower than the literature.",
    },
    {
        "id": "PRO-004",
        "module": "Protocol Literacy",
        "audience": "technician",
        "question": "What about accelerated protocols and SNT/SAINT?",
        "claim": "Accelerated and Stanford Neuromodulation Therapy-style protocols show promising rapid effects in selected studies, but they require exact protocol fidelity and should not be improvised from standard rTMS.",
        "patient_answer": "Some research protocols deliver multiple sessions per day, but they are specialized and not the same as routine TMS.",
        "technician_detail": "Check intersession interval, pulse dose, target method, daily session count, and safety monitoring.",
        "evidence_strength": "moderate",
        "source_pmids": "32252538; 34711062",
        "clinical_action": "Label accelerated protocols as separate workflows.",
        "caveat": "Evidence base, regulatory status, and clinic readiness vary.",
    },
    {
        "id": "PRO-005",
        "module": "Protocol Literacy",
        "audience": "technician",
        "question": "Are deep TMS and figure-8 rTMS interchangeable?",
        "claim": "Deep TMS and figure-8 coil rTMS use different coil designs, field distributions, protocols, and device-specific evidence; they are not interchangeable at the technician level.",
        "patient_answer": "Different TMS devices can stimulate in different ways, so the treatment plan is device-specific.",
        "technician_detail": "Follow device-specific training, safety procedures, helmet/coil positioning, and protocol parameters.",
        "evidence_strength": "strong",
        "source_pmids": "31901449; 27090022; 33243615",
        "clinical_action": "Maintain separate competency checklists by device.",
        "caveat": "Device-specific manuals and FDA labeling should be added to the evidence base.",
    },
    {
        "id": "PRO-006",
        "module": "Protocol Literacy",
        "audience": "patient_and_technician",
        "question": "Can depression evidence be applied to OCD, smoking, migraine, pain, or other conditions?",
        "claim": "Evidence and cleared indications differ by condition; technicians should not generalize depression protocol claims to other diagnoses.",
        "patient_answer": "TMS is studied for several conditions, but each condition has its own evidence and protocol.",
        "technician_detail": "Use condition-specific protocol orders and patient education language.",
        "evidence_strength": "strong",
        "source_pmids": "31901449; 33243615",
        "clinical_action": "Separate diagnosis-specific modules.",
        "caveat": "Regulatory clearance can differ from guideline evidence and from local clinical practice.",
    },
    {
        "id": "PRO-007",
        "module": "Protocol Literacy",
        "audience": "technician",
        "question": "Why are dose variables not convenience variables?",
        "claim": "Frequency, train duration, intertrain interval, intensity, pulse count, target, and session spacing are active treatment variables.",
        "patient_answer": "The timing and number of pulses are part of the prescription.",
        "technician_detail": "Do not alter pulse count, spacing, or intensity to fit scheduling unless a clinician-approved protocol allows it.",
        "evidence_strength": "strong",
        "source_pmids": "33243615; 9474057; 31901449",
        "clinical_action": "Build hard stops for protocol deviations.",
        "caveat": "Some devices automate these fields; technicians still need to verify them.",
    },
    {
        "id": "PRO-008",
        "module": "Protocol Literacy",
        "audience": "technician",
        "question": "How should clinical outcomes be tracked?",
        "claim": "Treatment response should be tracked with validated clinical measures and clinician assessment, not technician intuition alone.",
        "patient_answer": "The rating scales help the team measure change over time.",
        "technician_detail": "Administer scales exactly as assigned and escalate suicidality or deterioration immediately.",
        "evidence_strength": "strong",
        "source_pmids": "28541649; 27090022",
        "clinical_action": "Integrate scale due dates into workflow.",
        "caveat": "Scale choice is clinic- and diagnosis-specific.",
    },
    {
        "id": "MEAS-001",
        "module": "Future Expansion: fNIRS, EEG, qEEG, TMS-EEG",
        "audience": "technician",
        "question": "What can fNIRS add?",
        "claim": "fNIRS can measure cortical hemodynamic signals during or around stimulation, but TMS/fNIRS workflows remain emerging and protocol-specific.",
        "patient_answer": "fNIRS is a way to measure blood-flow-related brain activity near the scalp; it is not required for standard TMS everywhere.",
        "technician_detail": "Optode placement, hair, motion, ambient light, and timing relative to stimulation can affect signal quality.",
        "evidence_strength": "limited",
        "source_pmids": "41478613; 42055949",
        "clinical_action": "Pilot fNIRS as a research/QA workflow before clinical claims.",
        "caveat": "Evidence is not yet sufficient for universal response prediction.",
    },
    {
        "id": "MEAS-002",
        "module": "Future Expansion: fNIRS, EEG, qEEG, TMS-EEG",
        "audience": "technician",
        "question": "What can EEG or qEEG add?",
        "claim": "EEG/qEEG may support precision-medicine research for noninvasive brain stimulation in depression, but biomarker-guided decisions remain an emerging area.",
        "patient_answer": "Brain-wave tests may provide useful information in some settings, but they do not guarantee who will respond.",
        "technician_detail": "Training must cover electrode quality, artifact management, state control, and who is qualified to interpret outputs.",
        "evidence_strength": "moderate",
        "source_pmids": "41483580",
        "clinical_action": "Avoid deterministic qEEG marketing language.",
        "caveat": "Algorithm-specific validation is needed before clinical decision use.",
    },
    {
        "id": "MEAS-003",
        "module": "Future Expansion: fNIRS, EEG, qEEG, TMS-EEG",
        "audience": "technician",
        "question": "What is TMS-EEG?",
        "claim": "TMS-EEG measures EEG responses to TMS pulses and can probe cortical reactivity, but stimulation artifacts and preprocessing choices are major technical challenges.",
        "patient_answer": "TMS-EEG records brain electrical activity around the TMS pulse, usually for specialized testing or research.",
        "technician_detail": "Cap setup, electrode impedance, amplifier protection, artifact correction, timing, and patient movement are core workflow burdens.",
        "evidence_strength": "moderate",
        "source_pmids": "42055012; 42066923; 41344323",
        "clinical_action": "Treat TMS-EEG as a separate competency.",
        "caveat": "Outputs need expert interpretation and validated preprocessing.",
    },
    {
        "id": "MEAS-004",
        "module": "Future Expansion: fNIRS, EEG, qEEG, TMS-EEG",
        "audience": "technician",
        "question": "How should measurement tools be introduced into the platform?",
        "claim": "Measurement tools should be organized by readiness level: clinic-ready workflow, clinic-QA tool, research-use biomarker, or investigational method.",
        "patient_answer": "Some measurements are routine, while others are still research tools.",
        "technician_detail": "Each measurement module should state setup burden, artifact risks, interpretation authority, and clinical decision pathway.",
        "evidence_strength": "strong",
        "source_pmids": "41483580; 42055012; 42066923",
        "clinical_action": "Add readiness labels before expanding into qEEG/fNIRS modules.",
        "caveat": "Readiness may change as local validation and new evidence accumulate.",
    },
]

CLAIMS.extend(
    [
        {
            "id": "MEC-009",
            "module": "Mechanisms",
            "audience": "technician",
            "question": "What does personalized targeting add?",
            "claim": "Personalized targeting and electric-field-informed workflows can improve anatomical or circuit precision, but they require additional imaging, modeling, QA, and interpretation infrastructure.",
            "patient_answer": "Some programs use imaging to personalize the target. That can make placement more specific, but it is a specialized workflow.",
            "technician_detail": "Do not treat personalized, neuronavigated, robotic, or circuit-guided targeting as a simple coordinate substitution.",
            "evidence_strength": "moderate",
            "source_pmids": "42204340; 42044040; 41438652",
            "clinical_action": "Create separate competencies for MRI-guided and circuit-guided workflows.",
            "caveat": "Precision workflows do not automatically prove superior outcomes in every setting.",
        },
        {
            "id": "MEC-010",
            "module": "Mechanisms",
            "audience": "patient_and_technician",
            "question": "Is TMS the same as ECT?",
            "claim": "TMS is a nonconvulsive outpatient neuromodulation technique and is mechanistically and procedurally distinct from electroconvulsive therapy.",
            "patient_answer": "TMS is not ECT. It does not require anesthesia and is not intended to cause a seizure.",
            "technician_detail": "Use this distinction when patients arrive with fear based on ECT assumptions.",
            "evidence_strength": "strong",
            "source_pmids": "28541649; 27090022; 33243615",
            "clinical_action": "Include a TMS-versus-ECT misconception item in onboarding.",
            "caveat": "ECT remains an evidence-based treatment for some conditions; avoid stigmatizing comparisons.",
        },
        {
            "id": "SAF-009",
            "module": "Safety and Side Effects",
            "audience": "technician",
            "question": "How should pregnancy or special populations be handled?",
            "claim": "Pregnancy, adolescence, older age, epilepsy, implanted devices, and complex neurological or psychiatric histories require clinician-level review rather than technician-level clearance.",
            "patient_answer": "Some medical situations do not automatically rule out TMS, but they do require careful clinician review.",
            "technician_detail": "Do not reassure or exclude independently; escalate to the prescriber or medical director.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 19833552; 40865772; 40429604",
            "clinical_action": "Build special-population flags into intake and daily screening.",
            "caveat": "Evidence differs substantially by subgroup and indication.",
        },
        {
            "id": "SAF-010",
            "module": "Safety and Side Effects",
            "audience": "technician",
            "question": "How should implanted devices be handled?",
            "claim": "Implanted electronic devices and ferromagnetic or conductive material near the stimulation path are safety-review triggers because magnetic fields can interact with hardware.",
            "patient_answer": "We ask about implants because magnets can interact with certain devices or metal.",
            "technician_detail": "Document device type, location, manufacturer information if available, and clinician clearance.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 19833552; 9803953; 9918361",
            "clinical_action": "Maintain an implant-escalation checklist.",
            "caveat": "Compatibility decisions may require device manuals or manufacturer consultation.",
        },
        {
            "id": "SAF-011",
            "module": "Safety and Side Effects",
            "audience": "patient_and_technician",
            "question": "How should headache be discussed?",
            "claim": "Headache after TMS is usually transient, but severe, unusual, or persistent headache should be escalated rather than dismissed.",
            "patient_answer": "Mild headache can happen. Please tell us if it is severe, unusual, or does not settle the way it normally does.",
            "technician_detail": "Offer only clinic-approved comfort measures and route medication questions to clinical staff.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 28541649; 27090022",
            "clinical_action": "Add headache severity and timing fields to adverse-event documentation.",
            "caveat": "Do not give individualized medication advice outside scope.",
        },
        {
            "id": "SAF-012",
            "module": "Safety and Side Effects",
            "audience": "technician",
            "question": "Why track postmarketing and adverse-event signals?",
            "claim": "Postmarketing adverse-event surveillance can identify real-world safety patterns that may not be fully visible in trials.",
            "patient_answer": "Clinics track side effects so safety practices can keep improving.",
            "technician_detail": "Adverse-event documentation should be structured enough to support internal QA and required reporting pathways.",
            "evidence_strength": "moderate",
            "source_pmids": "41678387; 34133991",
            "clinical_action": "Train technicians on what counts as reportable internally.",
            "caveat": "Spontaneous-report databases have reporting bias and cannot estimate incidence alone.",
        },
        {
            "id": "FAQ-011",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "If I feel better, can I stop early?",
            "claim": "Stopping early should be a clinician decision because standard courses are designed around cumulative dosing and measured response.",
            "patient_answer": "Feeling better is important, but talk with the treatment team before changing the treatment schedule.",
            "technician_detail": "Route early-stop requests to the prescriber and continue objective symptom tracking.",
            "evidence_strength": "clinic-policy-dependent",
            "source_pmids": "28541649; 27090022",
            "clinical_action": "Add early-improvement counseling to FAQ scripts.",
            "caveat": "Continuation, taper, maintenance, and retreatment protocols vary.",
        },
        {
            "id": "FAQ-012",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "What if I am anxious during treatment?",
            "claim": "Anxiety and expectancy can affect the patient experience, so calm coaching, accurate expectations, and symptom reporting are part of good TMS care.",
            "patient_answer": "It is common to feel nervous at first. Tell us what you feel so we can coach you through what is expected and what needs attention.",
            "technician_detail": "Use neutral reassurance and avoid promising response or minimizing concerns.",
            "evidence_strength": "limited",
            "source_pmids": "41812418; 42090145",
            "clinical_action": "Teach first-session scripts and distress-escalation triggers.",
            "caveat": "Expectancy effects are real but should not be used to imply symptoms are imagined.",
        },
        {
            "id": "FAQ-013",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "Is twitching normal?",
            "claim": "Facial or scalp muscle twitching can occur because the magnetic field activates superficial nerves and muscles near the coil.",
            "patient_answer": "Some twitching around the scalp, forehead, or face can be normal. Tell us if it changes, hurts, or feels unusual.",
            "technician_detail": "Differentiate expected superficial activation from unintended limb movement, seizure concern, or coil misplacement.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 19833552",
            "clinical_action": "Include expected movement sensations in first-session education.",
            "caveat": "New or excessive movement should trigger setup review.",
        },
        {
            "id": "FAQ-014",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "How does TMS work?",
            "claim": "TMS uses a rapidly changing magnetic field to induce small electric fields in brain tissue, rather than sending electricity directly through the scalp.",
            "patient_answer": "The coil makes a brief magnetic pulse. That pulse passes through the scalp and induces tiny electrical currents in the targeted brain area.",
            "technician_detail": "Use magnetic induction language and avoid implying direct electrical injection or a simple mood switch.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 19833552",
            "clinical_action": "Add a plain-language mechanism script to first-session onboarding.",
            "caveat": "Mechanism language does not predict individual response.",
        },
        {
            "id": "FAQ-015",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "Why do I need so many sessions?",
            "claim": "Clinical TMS courses use repeated sessions because effects are expected to accumulate across a treatment course rather than occur only during one stimulation event.",
            "patient_answer": "Each session is part of a course. The goal is for effects to build over repeated treatments, so sticking with the schedule matters.",
            "technician_detail": "Frame adherence as cumulative dosing while avoiding promises about when or whether response will occur.",
            "evidence_strength": "strong",
            "source_pmids": "31901449; 28541649; 27090022",
            "clinical_action": "Connect missed-session counseling to the repeated-session rationale.",
            "caveat": "Course length and schedule depend on the prescribed protocol and clinical response.",
        },
        {
            "id": "FAQ-016",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "What is motor threshold?",
            "claim": "Resting motor threshold is a personalized calibration measure used to scale treatment intensity, not a measure of mood severity or treatment success.",
            "patient_answer": "The hand or thumb movement test helps the team set your dose. It is not a test of how depressed you are or whether you are improving.",
            "technician_detail": "Explain RMT as a dosing calibration step and document method, muscle/site, intensity, and retest triggers.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 41949547; 42082007",
            "clinical_action": "Add motor-threshold explanation to mapping and remapping workflows.",
            "caveat": "RMT methods vary; clinics should follow their device and protocol SOP.",
        },
        {
            "id": "FAQ-017",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "What side effects are common?",
            "claim": "Common TMS side effects are usually local and transient, including scalp discomfort, headache, facial twitching, and fatigue.",
            "patient_answer": "The most common issues are temporary scalp discomfort, headache, twitching near the coil, or fatigue. Tell us if anything is intense, unusual, or worsening.",
            "technician_detail": "Track side effect type, severity, timing, session context, comfort steps, and whether clinician review was needed.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 19833552; 28541649; 27090022",
            "clinical_action": "Use a structured side-effect check-in at every session.",
            "caveat": "Common does not mean ignorable; severe or unusual symptoms require escalation.",
        },
        {
            "id": "FAQ-018",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "How rare are seizures?",
            "claim": "TMS-associated seizure is rare when safety guidelines and screening are followed, but it remains the serious acute event technicians must be trained to recognize and manage.",
            "patient_answer": "Seizures are rare, and that is why we screen carefully and follow safety procedures at every visit.",
            "technician_detail": "Know the clinic seizure-response procedure, stop stimulation immediately, protect the patient, and summon medical help.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 19833552; 34133991; 9474057",
            "clinical_action": "Teach seizure risk with both reassurance and emergency readiness.",
            "caveat": "Risk depends on protocol, device, history, medications, sleep, substances, and other factors.",
        },
        {
            "id": "FAQ-019",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "Why do I need ear protection?",
            "claim": "Ear protection is recommended because TMS coils produce loud clicking sounds, and hearing protection is a low-burden safety step.",
            "patient_answer": "The earplugs are for the clicking sound from the coil. They help protect your hearing during treatment.",
            "technician_detail": "Confirm hearing protection before stimulation and document exceptions, intolerance, or hearing-related complaints.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 19833552; 1549231",
            "clinical_action": "Make ear protection a visible pre-session checkpoint.",
            "caveat": "Patients with hearing devices, tinnitus, or ear symptoms may need individualized review.",
        },
        {
            "id": "FAQ-020",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "Can TMS trigger mania or feeling too activated?",
            "claim": "Mood switching or manic/hypomanic activation is uncommon but important to detect, especially when sleep, energy, impulsivity, or agitation changes rapidly.",
            "patient_answer": "Tell us if you feel unusually energized, need much less sleep, feel impulsive, agitated, or unlike yourself.",
            "technician_detail": "Escalate suspected manic, hypomanic, mixed, or unsafe activation symptoms to the treating clinician before continuing.",
            "evidence_strength": "moderate",
            "source_pmids": "33243615; 28541649; 31901449",
            "clinical_action": "Include activation and sleep-change prompts in mood safety screening.",
            "caveat": "Assessment depends on diagnosis, medication plan, and clinician judgment.",
        },
        {
            "id": "FAQ-021",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "Is TMS the same as ECT?",
            "claim": "TMS is procedurally and mechanistically distinct from electroconvulsive therapy: it is outpatient, nonconvulsive, and does not require anesthesia.",
            "patient_answer": "TMS is not ECT. You stay awake, it does not require anesthesia, and the treatment is not intended to cause a seizure.",
            "technician_detail": "Use this distinction to reduce fear while avoiding dismissive or stigmatizing comparisons to ECT.",
            "evidence_strength": "strong",
            "source_pmids": "28541649; 27090022; 33243615",
            "clinical_action": "Add TMS-versus-ECT language to intake scripts.",
            "caveat": "ECT is an evidence-based treatment in appropriate clinical situations; do not frame it as inferior or unsafe.",
        },
        {
            "id": "FAQ-022",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "What if I have an implant or metal?",
            "claim": "Implanted electronic devices and ferromagnetic or conductive material near the stimulation path are safety-review triggers because TMS magnetic fields can interact with hardware.",
            "patient_answer": "Tell us about any implants, devices, metal, shrapnel, aneurysm clips, stimulators, or hearing devices. The clinical team will review whether treatment is safe.",
            "technician_detail": "Document device type, location, manufacturer/model when available, and clinician clearance before stimulation.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 19833552; 9803953; 9918361",
            "clinical_action": "Add an implant and metal escalation script to daily screening.",
            "caveat": "Compatibility decisions may require device manuals, manufacturer information, imaging history, or specialist input.",
        },
        {
            "id": "FAQ-023",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "What about pregnancy, age, or complex medical situations?",
            "claim": "Pregnancy, adolescence, older age, epilepsy, implanted devices, and complex neurological or psychiatric histories require clinician-level review rather than technician-level clearance.",
            "patient_answer": "These situations do not always mean TMS is impossible, but they do mean the clinician needs to review your specific case.",
            "technician_detail": "Do not reassure, exclude, or clear independently; collect the relevant details and escalate through the prescriber or medical director.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 19833552; 40865772; 40429604",
            "clinical_action": "Create special-population flags in intake and daily update workflows.",
            "caveat": "Evidence differs by subgroup, diagnosis, protocol, and risk profile.",
        },
        {
            "id": "FAQ-024",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "What if I get a headache?",
            "claim": "Headache after TMS is usually transient, but severe, unusual, worsening, or persistent headache should be escalated rather than dismissed.",
            "patient_answer": "Mild headache can happen. Please tell us if it is severe, unusual for you, getting worse, or not settling the way it normally does.",
            "technician_detail": "Use clinic-approved comfort steps only and route medication or concerning symptom questions to clinical staff.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 28541649; 27090022",
            "clinical_action": "Add headache timing, severity, and pattern fields to adverse-event documentation.",
            "caveat": "Do not give individualized medication advice outside scope.",
        },
        {
            "id": "FAQ-025",
            "module": "Patient FAQ",
            "audience": "patient",
            "question": "Will I need maintenance or another course later?",
            "claim": "Maintenance and retreatment approaches exist, but they are less standardized than acute-course protocols and should be individualized by the treating clinician.",
            "patient_answer": "Some patients discuss maintenance or another course later, but that plan depends on your response, relapse risk, symptoms, coverage, and clinician judgment.",
            "technician_detail": "Avoid implying a universal maintenance schedule; document response, relapse concerns, and clinician orders.",
            "evidence_strength": "moderate",
            "source_pmids": "28541649; 27090022",
            "clinical_action": "Add maintenance and retreatment boundaries to discharge or end-of-course scripts.",
            "caveat": "Maintenance frequency, duration, coverage, and evidence differ by clinic and indication.",
        },
        {
            "id": "TEC-011",
            "module": "Technician Workflow",
            "audience": "technician",
            "question": "What is the technician scope boundary?",
            "claim": "Technicians can execute, monitor, document, and escalate, but diagnosis, eligibility, protocol selection, and medication decisions belong to qualified clinicians.",
            "patient_answer": "Technicians help deliver the treatment safely and communicate changes to the clinical team.",
            "technician_detail": "Use scripted escalation instead of improvising clinical advice.",
            "evidence_strength": "strong",
            "source_pmids": "28541649; 27090022; 33243615",
            "clinical_action": "Make scope boundaries explicit in competency training.",
            "caveat": "Specific legal scope varies by jurisdiction and clinic policy.",
        },
        {
            "id": "TEC-012",
            "module": "Technician Workflow",
            "audience": "technician",
            "question": "How should device-specific training be handled?",
            "claim": "Device, coil, helmet, neuronavigation, and software workflows require device-specific training in addition to general TMS knowledge.",
            "patient_answer": "The equipment setup is specific to the device and your treatment plan.",
            "technician_detail": "Maintain device-specific checkoffs for startup, calibration, coil/helmet placement, fault handling, and shutdown.",
            "evidence_strength": "strong",
            "source_pmids": "33243615; 27090022",
            "clinical_action": "Separate general TMS education from device competency.",
            "caveat": "Manufacturer manuals and local SOPs are required evidence sources beyond PubMed.",
        },
        {
            "id": "TEC-013",
            "module": "Technician Workflow",
            "audience": "technician",
            "question": "How should suicidality be handled during a depression course?",
            "claim": "Worsening suicidality or emergent acute risk should be escalated immediately through the clinic's psychiatric safety pathway.",
            "patient_answer": "If suicidal thoughts worsen or feel urgent, tell us immediately or seek emergency help.",
            "technician_detail": "Do not wait for the next rating-scale interval when acute risk is disclosed.",
            "evidence_strength": "strong",
            "source_pmids": "28541649; 27090022; 41819354",
            "clinical_action": "Integrate suicide-risk escalation into technician scripts.",
            "caveat": "Emergency response must follow local law and clinic policy.",
        },
        {
            "id": "PRO-009",
            "module": "Protocol Literacy",
            "audience": "technician",
            "question": "What about maintenance or retreatment?",
            "claim": "Maintenance and retreatment approaches exist, but they are less standardized than acute-course protocols and should be clinician-directed.",
            "patient_answer": "Some people discuss maintenance or another course later, but that plan is individualized.",
            "technician_detail": "Do not imply a universal maintenance schedule; document relapse, response, and clinician orders.",
            "evidence_strength": "moderate",
            "source_pmids": "28541649; 27090022",
            "clinical_action": "Create a separate maintenance/retreatment module.",
            "caveat": "Coverage and evidence differ by diagnosis and setting.",
        },
        {
            "id": "PRO-010",
            "module": "Protocol Literacy",
            "audience": "technician",
            "question": "How should special-age populations be taught?",
            "claim": "Youth and late-life depression TMS evidence is growing, but protocols and safety considerations should be handled as special-population workflows.",
            "patient_answer": "Age and medical context can affect how the team plans and monitors treatment.",
            "technician_detail": "Escalate cognitive impairment, frailty, guardian/consent issues, or pediatric considerations.",
            "evidence_strength": "moderate",
            "source_pmids": "40865772; 40429604; 28541649",
            "clinical_action": "Add special-population branching in training.",
            "caveat": "Evidence from general adult MDD should not be applied automatically.",
        },
        {
            "id": "PRO-011",
            "module": "Protocol Literacy",
            "audience": "patient_and_technician",
            "question": "How should placebo and expectancy be discussed?",
            "claim": "Expectancy and placebo-related effects can influence mood and treatment experience, but they do not make TMS 'just placebo'.",
            "patient_answer": "Expectations can affect how treatment feels, but TMS also has protocol-specific biological effects being studied and used clinically.",
            "technician_detail": "Use balanced language: optimistic, accurate, and free of guaranteed outcomes.",
            "evidence_strength": "moderate",
            "source_pmids": "42090145; 28541649; 17573044",
            "clinical_action": "Train neutral expectation-setting.",
            "caveat": "Placebo-control designs differ across protocols and devices.",
        },
        {
            "id": "PRO-012",
            "module": "Protocol Literacy",
            "audience": "technician",
            "question": "How should FDA clearance and literature evidence be separated?",
            "claim": "Regulatory clearance, payer coverage, guideline support, and research evidence are related but distinct categories.",
            "patient_answer": "Whether a protocol is offered depends on evidence, approval status, coverage, and clinician judgment.",
            "technician_detail": "Training content should label each protocol as clinic-approved, guideline-supported, FDA-cleared where applicable, or investigational.",
            "evidence_strength": "strong",
            "source_pmids": "31901449; 28541649; 33243615",
            "clinical_action": "Add evidence-status labels to protocol cards.",
            "caveat": "Regulatory status must be verified from FDA/device sources, not PubMed alone.",
        },
        {
            "id": "MEAS-005",
            "module": "Future Expansion: fNIRS, EEG, qEEG, TMS-EEG",
            "audience": "technician",
            "question": "What is the main artifact risk in TMS-EEG?",
            "claim": "TMS-EEG is vulnerable to large pulse-related, muscle, auditory, somatosensory, and equipment artifacts that can dominate the measured signal if not controlled.",
            "patient_answer": "When EEG is combined with TMS, the team has to separate brain signals from stimulation-related noise.",
            "technician_detail": "Artifact control starts before analysis: cap preparation, coil positioning, hearing masking/ear protection, impedance, and motion control matter.",
            "evidence_strength": "moderate",
            "source_pmids": "42055012; 42066923",
            "clinical_action": "Build a TMS-EEG artifact checklist.",
            "caveat": "Preprocessing decisions can change interpretation.",
        },
        {
            "id": "MEAS-006",
            "module": "Future Expansion: fNIRS, EEG, qEEG, TMS-EEG",
            "audience": "technician",
            "question": "Who should interpret qEEG or biomarker outputs?",
            "claim": "Biomarker outputs should be interpreted by qualified clinicians or researchers within a validated workflow, not by technicians from raw displays alone.",
            "patient_answer": "Specialized brain-signal results need expert interpretation.",
            "technician_detail": "Technician responsibilities should focus on high-quality acquisition, artifact notes, and escalation of technical issues.",
            "evidence_strength": "strong",
            "source_pmids": "41483580; 33243615",
            "clinical_action": "Define acquisition versus interpretation roles.",
            "caveat": "Local credentialing and device claims may vary.",
        },
        {
            "id": "MEAS-007",
            "module": "Future Expansion: fNIRS, EEG, qEEG, TMS-EEG",
            "audience": "technician",
            "question": "What makes fNIRS quality fragile?",
            "claim": "fNIRS signal quality can be affected by optode contact, hair, motion, superficial blood flow, ambient light, and task timing.",
            "patient_answer": "Good sensor contact and staying still help the recording quality.",
            "technician_detail": "Training should include optode placement, signal-quality checks, motion notes, and exclusion criteria.",
            "evidence_strength": "limited",
            "source_pmids": "41478613; 42055949",
            "clinical_action": "Do fNIRS dry runs before using it in a treatment workflow.",
            "caveat": "TMS/fNIRS evidence in psychiatric treatment is still early.",
        },
        {
            "id": "MEAS-008",
            "module": "Future Expansion: fNIRS, EEG, qEEG, TMS-EEG",
            "audience": "technician",
            "question": "How should data privacy be handled for added measurement tools?",
            "claim": "Adding EEG, qEEG, fNIRS, imaging, or biomarker data increases privacy, storage, and interpretation responsibilities beyond routine treatment logs.",
            "patient_answer": "Additional brain measurements create additional health data that must be handled carefully.",
            "technician_detail": "Know consent status, file naming, storage location, access limits, and whether data are clinical or research records.",
            "evidence_strength": "clinic-policy-dependent",
            "source_pmids": "33243615",
            "clinical_action": "Add data-governance training before multimodal expansion.",
            "caveat": "This requires local privacy/legal policy beyond PubMed evidence.",
        },
        {
            "id": "MEAS-009",
            "module": "Future Expansion: fNIRS, EEG, qEEG, TMS-EEG",
            "audience": "technician",
            "question": "When should multimodal measurement be added?",
            "claim": "Multimodal measurement should be added only when there is a defined clinical, QA, or research question and a plan for acting on or interpreting the data.",
            "patient_answer": "Extra measurements should have a clear purpose, not just create more data.",
            "technician_detail": "Every added modality needs a decision pathway, artifact policy, and responsible interpreter.",
            "evidence_strength": "strong",
            "source_pmids": "41483580; 42055012; 42066923",
            "clinical_action": "Require a modality purpose statement in future modules.",
            "caveat": "Exploratory research protocols can collect data without immediate clinical action if consented and governed appropriately.",
        },
    ]
)


def load_records() -> dict[str, dict[str, str]]:
    with RECORDS_PATH.open(newline="", encoding="utf-8") as handle:
        return {row["pmid"]: row for row in csv.DictReader(handle)}


def source_labels(pmids: str, records: dict[str, dict[str, str]]) -> str:
    labels = []
    for pmid in [item.strip() for item in pmids.split(";") if item.strip()]:
        row = records.get(pmid)
        if row:
            labels.append(f"{pmid}: {row['title']}")
        else:
            labels.append(f"{pmid}: MISSING_FROM_CORPUS")
    return " | ".join(labels)


def write_claims(records: dict[str, dict[str, str]]) -> None:
    fields = [
        "claim_id",
        "module",
        "audience",
        "question",
        "claim",
        "patient_answer",
        "technician_detail",
        "evidence_strength",
        "source_pmids",
        "source_labels",
        "clinical_action",
        "caveat",
        "status",
    ]
    with CLAIMS_PATH.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for claim in CLAIMS:
            row = {
                "claim_id": claim["id"],
                "module": claim["module"],
                "audience": claim["audience"],
                "question": claim["question"],
                "claim": claim["claim"],
                "patient_answer": claim["patient_answer"],
                "technician_detail": claim["technician_detail"],
                "evidence_strength": claim["evidence_strength"],
                "source_pmids": claim["source_pmids"],
                "source_labels": source_labels(claim["source_pmids"], records),
                "clinical_action": claim["clinical_action"],
                "caveat": claim["caveat"],
                "status": "ready_for_training_draft_after_full_text_QA",
            }
            writer.writerow(row)


def write_patient_markdown() -> None:
    patient_claims = [
        claim
        for claim in CLAIMS
        if claim["audience"] in {"patient", "patient_and_technician"}
    ]
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for claim in patient_claims:
        grouped[claim["module"]].append(claim)
    with PATIENT_MD.open("w", encoding="utf-8") as handle:
        handle.write("# Patient FAQ Claim Draft\n\n")
        handle.write("These are source-linked claim drafts for technician-delivered patient education. They should be adapted to clinic policy and clinician-approved scripts before release.\n\n")
        for module, claims in grouped.items():
            handle.write(f"## {module}\n\n")
            for claim in claims:
                handle.write(f"### {claim['question']}\n\n")
                handle.write(f"{claim['patient_answer']}\n\n")
                handle.write(f"- Evidence strength: `{claim['evidence_strength']}`\n")
                handle.write(f"- Sources: `{claim['source_pmids']}`\n")
                handle.write(f"- Boundary: {claim['caveat']}\n\n")


def write_technician_markdown() -> None:
    tech_claims = [
        claim
        for claim in CLAIMS
        if claim["audience"] in {"technician", "patient_and_technician"}
    ]
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for claim in tech_claims:
        grouped[claim["module"]].append(claim)
    with TECH_MD.open("w", encoding="utf-8") as handle:
        handle.write("# Technician Workflow Claim Draft\n\n")
        handle.write("These claims are intended for SOPs, checklists, and technician education. They are not a substitute for device manuals, prescriber orders, or local emergency policy.\n\n")
        for module, claims in grouped.items():
            handle.write(f"## {module}\n\n")
            for claim in claims:
                handle.write(f"### {claim['question']}\n\n")
                handle.write(f"- Claim: {claim['claim']}\n")
                handle.write(f"- Technician detail: {claim['technician_detail']}\n")
                handle.write(f"- Training action: {claim['clinical_action']}\n")
                handle.write(f"- Evidence strength: `{claim['evidence_strength']}`\n")
                handle.write(f"- Sources: `{claim['source_pmids']}`\n")
                handle.write(f"- Boundary: {claim['caveat']}\n\n")


def write_coverage(records: dict[str, dict[str, str]]) -> None:
    module_counts = Counter(claim["module"] for claim in CLAIMS)
    strength_counts = Counter(claim["evidence_strength"] for claim in CLAIMS)
    source_counts: Counter[str] = Counter()
    missing: list[str] = []
    for claim in CLAIMS:
        for pmid in [item.strip() for item in claim["source_pmids"].split(";") if item.strip()]:
            source_counts[pmid] += 1
            if pmid not in records:
                missing.append(pmid)

    with COVERAGE_MD.open("w", encoding="utf-8") as handle:
        handle.write("# Claim Source Coverage\n\n")
        handle.write(f"Total extracted claims: {len(CLAIMS)}\n\n")
        handle.write("## Claims By Module\n\n")
        for module, count in module_counts.most_common():
            handle.write(f"- `{module}`: {count}\n")
        handle.write("\n## Claims By Evidence Strength\n\n")
        for strength, count in strength_counts.most_common():
            handle.write(f"- `{strength}`: {count}\n")
        handle.write("\n## Most Used Sources\n\n")
        for pmid, count in source_counts.most_common():
            title = records.get(pmid, {}).get("title", "MISSING_FROM_CORPUS")
            handle.write(f"- `{pmid}` ({count} claims): {title}\n")
        handle.write("\n## Missing PMIDs\n\n")
        if missing:
            for pmid in sorted(set(missing)):
                handle.write(f"- `{pmid}`\n")
        else:
            handle.write("None. Every claim source PMID is present in `pubmed_records.csv`.\n")


def main() -> int:
    records = load_records()
    write_claims(records)
    write_patient_markdown()
    write_technician_markdown()
    write_coverage(records)
    print(f"Wrote {CLAIMS_PATH}")
    print(f"Wrote {PATIENT_MD}")
    print(f"Wrote {TECH_MD}")
    print(f"Wrote {COVERAGE_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
